server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    issuer: "user-service"
    private-key-path: "jwt-keys/jwt-private.der"
    public-key-path: "jwt-keys/jwt-public.der"
    expires-in-seconds: 3600